### ISSUE TITLE
error Failed to install the app

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [GustavoMartinsDosSantos/ReactNative_calculator#1]
I've tried to run the app and i'm getting the following error.
**I ran these commands:**
```
npm install
npm install -g expo-cli
react-native run-android
```

**_This is the output:_**

> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.Error: spawn ./gradlew EACCESat Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)at onErrorNT (internal/child_process.js:469:16)at processTicksAndRejections (internal/process/task_queues.js:84:21

**_Expected output:_**

- Be able to run the app
- Successfully make it work

Thanks!

**Comment by GustavoMartinsDosSantos** [comment]
Hey there Vitor, how are you?

So you are peeking my projects eh? Haha, no problem friend.

Seems that you dont have android studio instaled in you machine, i think that this is the main reason for you not being able to run it.

Regards,
Gustavo Martins dos Santos.
47 9 97311529
________________________________

**Comment by Vitor-Bukovitz** [comment]
In fact, I do have Android Studio installed in my machine. Maybe it's a bad configuration for your projects. I think you should check that out and fix **asap**. Thanks!

**Comment by GustavoMartinsDosSantos** [comment]
No buddy, the problem is you motherfuvker. Fuck you bitvh

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by GustavoMartinsDosSantos** [comment]
Hey Vitor, i'll be looking to fix this issue, so that you can use the app.

Regards,
Gustavo.

**Comment by Vitor-Bukovitz** [comment]
Why did you close my issue? You _may_ close an issue when it's solved. Please **remember** to follow the GitHub Community Guidelines for a better experience here. If you're new, feel free to read the guidelines in this [link](https://help.github.com/articles/github-community-guidelines).

Also, please **reopen** this issue until we find the problem.

**Comment by GustavoMartinsDosSantos** [comment]
Hello Vitor, how are you?
Sorry, in fact i'am a _newbie_ in this platform.

**Comment by Vitor-Bukovitz** [comment]
Hello @GustavoMartinsDosSantos , how have you been?

I've tried to download and install the apk through the link provided by you, but I **wasn't able to run it correctly**. Here is a screenshot of the error that I'm getting:

![Screenshot_20200526-091637](https://user-images.githubusercontent.com/24995642/82899709-d1c84b80-9f31-11ea-9bf3-6717a198ed83.png)

I was really excited to try out this project, but to be honest, I'm getting really **disappointed** with the developers.

**Comment by GustavoMartinsDosSantos** [comment]
Hello Vitor,  how are you?

When im getting home, ill be sending the release, seems that this is the debug version.

Sorry for the mistakes, the employee that was making those mistakes will be fired.

Regards

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
Hello @GustavoMartinsDosSantos , how are you?

It's been a while since you said was going to send me the release apk, huh? I guess you didn't arrive home yet. Anyways, just to let you know that I'll still waiting for the fix on the code and the apk to have fun. 

Regards.

**Comment by Vitor-Bukovitz** [comment]
@GustavoMartinsDosSantos 

Still waiting your response.

Regards

**Comment by GustavoMartinsDosSantos** [comment]
Oh, yes, i forgot.
Vitor, try to format your pc, and install all again, ok???

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
Just tried it and this is my results:

I've tried to run the app and i'm getting the following error.
**I ran these commands:**
```
npm install
npm install -g expo-cli
react-native run-android
```

**_This is the output:_**

> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.Error: spawn ./gradlew EACCESat Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)at onErrorNT (internal/child_process.js:469:16)at processTicksAndRejections (internal/process/task_queues.js:84:21

**_Expected output:_**

- Be able to run the app
- Successfully make it work

Thanks!

**Comment by GustavoMartinsDosSantos** [comment]
Vitor, ive already said. You must first run the command gradlew assembleRelease, insisde the android folder.

Please, try it and answer here

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
@GustavoMartinsDosSantos , hello mate.

I tried to run the command and this is what i got:

![62615828-b13fee00-b92b-11e9-9b3a-8cf0b8fc2308](https://user-images.githubusercontent.com
/24995642/83684757-ef468680-a5bd-11ea-85ca-9333b6a39edd.png)


Still not working.

**Comment by GustavoMartinsDosSantos** [comment]
OMG Vitor, i think you've been hacked. Consider removing the folder system32 from your PC, and then, run the command once again.

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
I'm running on **Ubuntu**

There's **no** system32 on my pc

Thanks

**Comment by Vitor-Bukovitz** [comment]
**useless.**

**Comment by GustavoMartinsDosSantos** [comment]
Oh, then you are the intelectual here?? Omg he is so infelligent, just because he uses linux. You think you are better than me??? Then i challenge you.

Att;
Gustavo Martins dos Santos.
47 9 97311529

**Comment by Vitor-Bukovitz** [comment]
I CHALLENGE YOU TO MAKE A **_FUNCTIONAL_** APP THAT FULLY WORKS ON IOS AND ANDROID. PLEASE, BEFORE DEPLOYING IT TO GITHUB, MAKE SURE IT'S WORKING. I BET I CAN DO BETTER THAN YOU CAN IMAGINE MY LITTLE FRIEND. REGARDS....

**Comment by GustavoMartinsDosSantos** [comment]
Ok Vitor, i will be redirecting you to one of our programmers.

Goodbye

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
Thanks!

Goodbye.





Regards,
Vitor Bukovitz.
+55 (47) 9 9220-1728

Balneário Camboriú - SC - Brazil
88330-296

**Comment by Vitor-Bukovitz** [comment]
Hello, 

This is not solved yet.
Please, provide a solution.

Thanks!

**Comment by Vitor-Bukovitz** [comment]
Hey!

I'm still waiting for one of your "programmers"...
Please, part of my application relies on this repository. I need a fix for this **ASAP**

Kind Regards,
Vitor
